### ISSUE TITLE
Not working on 1.20.3 (NoSuchMethodError)

### ISSUE THREAD

**Issue by ringo360** [CodeCrafter47/BungeeTabListPlus#746]
*Sorry, I using Translate. so my english is not good :/

## About this issue

BTLP 3.6.3 is not working on 1.20.3 😭 

> BungeeCord changed `PlayerListItem$Item#displayName`'s type to `BaseComponent`. A friend of mine said this is probably the cause.

## Log
Bungeecord server error log:
```java
21:00:32 [WARNING] A task raised an exception. Task: codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$$Lambda$2238/0x00007f8ac5c669f0@2e99ab97
java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setDisplayName(java.lang.String)'
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler$CustomContentTabOverlayHandler.update(NewTabOverlayHandler.java:742)
	at codecrafter47.bungeetablistplus.handler.NewTabOverlayHandler.update(NewTabOverlayHandler.java:359)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Spigot/Paper error log: *nothing.*

## How to reproduce this issue?

1. Download latest bungeecord(1.20.3)
2. Install latest BTLP
3. run bungeecord
4. Join server
5. When you look at the console, you will encounter this error.
## I tried...
* use different build version
* change from Waterfall to Bungeecord

## Server Version

BungeeCord: [Latest](https://ci.md-5.net/job/BungeeCord/1777/)(`build 1777 - 231024b`)

Purpur(Paper):
> I using several servers.

Server A:
```
Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-1858 (MC: 1.19.2)
* You are running the latest version
```
Server B:
```
This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
Previous version: git-Paper-411 (MC: 1.17.1)
  ```

**Comment by PrinceBunBun981** [comment]
Hey,

I've tested the latest Dev Build of BTLP (https://ci.codecrafter47.de/job/BungeeTabListPlus/lastSuccessfulBuild/) on Waterfall#556 and BungeeCord#1777 and am not encountering any errors.

Please try downloading the latest dev build, I know it shows as an older version than the version on Spigot, but trust me it is more up to date, just has the wrong number. :)

**Comment by ringo360** [comment]
Hmmmmmmmmm…
I'll try that.

**Comment by ringo360** [comment]
It works!
I tried and Successfully worked latest Dev Build.
thx <3

> But I'm a little confused by the different version designations and would like to see something done about it. Other users will probably make the same mistake.

**Comment by andfont** [comment]
It doesn't work, this case closed badly, it is mentioned in:
https://github.com/CodeCrafter47/BungeeTabListPlus/issues/747
